const Map<String, String> appLocalizationsEn = {
  'app_name': 'FabricOS',
  'tagline': 'AI operations platform for manufacturing.',
  'hero_title': 'Run manufacturing operations with predictive intelligence.',
  'hero_subtitle':
      'FabricOS helps operations teams manage maintenance, orders, suppliers, and ESG reporting from one dashboard.',
  'cta_start_trial': 'Start free trial',
  'cta_book_demo': 'Book a demo',
  'cta_get_started': 'Get started',
  'cta_sign_in': 'Sign in',
  'cta_sign_up': 'Sign up',
  'nav_features': 'Features',
  'nav_solutions': 'Solutions',
  'nav_pricing': 'Pricing',
  'nav_about': 'About',
  'nav_contact': 'Contact',
  'nav_faq': 'FAQ',
  'nav_roi': 'ROI',
  'nav_factory_audit': 'Factory score',
  'nav_book_demo': 'Book demo',
  'nav_case_studies': 'Case studies',
  'nav_blog': 'Blog',
  'nav_login': 'Log in',
  'nav_register': 'Register',
  'footer_privacy': 'Privacy Policy',
  'footer_terms': 'Terms of Service',
  'footer_cookies': 'Cookie Policy',
  'footer_contact': 'Contact',
  'login_title': 'Welcome back',
  'login_subtitle': 'Sign in to your account',
  'login_email': 'Email',
  'login_password': 'Password',
  'login_forgot': 'Forgot password?',
  'register_title': 'Create your account',
  'register_subtitle': 'Start your free trial',
  'register_name': 'Full name',
  'register_company': 'Company name',
  'forgot_title': 'Reset password',
  'forgot_subtitle': 'Enter your email to receive a reset link',
  'reset_title': 'Set new password',
  'dashboard': 'Dashboard',
  'products': 'Products',
  'product_detail': 'Product detail',
  'reorder_suggestions': 'Reorder suggestions',
  'forecasting': 'Forecasting',
  'suppliers': 'Suppliers',
  'alerts': 'Alerts',
  'purchase_orders': 'Purchase orders',
  'analytics': 'Analytics',
  'billing': 'Billing',
  'settings': 'Settings',
  'profile': 'Profile',
  'company': 'Company',
  'team': 'Team',
  'notifications': 'Notifications',
  'language': 'Language',
  'sign_out': 'Sign out',
  'products_at_risk': 'Products at risk',
  'overstocked': 'Overstocked',
  'reorder_today': 'Reorder today',
  'inventory_value': 'Inventory value',
  'capital_locked': 'Capital locked',
  'supplier_risk': 'Supplier risk',
  'empty_state_title': 'No data yet',
  'empty_state_subtitle': 'Import your first data or connect a source.',
  'onboarding_welcome': 'Welcome to FabricOS',
  'onboarding_company': 'Set up your company',
  'onboarding_data': 'Connect your data',
  'onboarding_done': "You're all set",
  'plan_starter': 'Starter',
  'plan_growth': 'Growth',
  'plan_pro': 'Pro',
  'plan_enterprise': 'Enterprise',
  'per_month': '/month',
  'per_year': '/year',
  'contact_sales': 'Contact sales',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'search': 'Search',
  'filter': 'Filter',
  'loading': 'Loading...',
  'error_generic': 'Something went wrong. Please try again.',
  'sku': 'SKU',
  'current_stock': 'Current stock',
  'reorder_point': 'Reorder point',
  'lead_time_days': 'Lead time (days)',
  'unit_cost': 'Unit cost',
  'selling_price': 'Selling price',
  'stock_coverage_days': 'Coverage (days)',
  'status_safe': 'Safe',
  'status_attention': 'Attention',
  'status_critical': 'Critical',
  'import_csv': 'Import CSV',
  'home': 'Home',
  'help': 'Help',
  'demo': 'Demo',
  'hero_headline_benefit':
      'Operate smarter with predictive maintenance and supply visibility',
  'hero_subheadline_one_line':
      'FabricOS gives manufacturing teams live control over machines, orders, suppliers, and compliance.',
  'cta_try_free': 'Try free',
  'cta_watch_demo': 'Watch demo',
  'cta_see_how': 'See how it works',
  'cta_start_now': 'Start now',
  'social_proof_title': 'Trusted by operations and supply chain teams',
  'social_proof_companies': '500+ companies',
  'social_proof_metric_stockout': '-22% stockouts',
  'social_proof_metric_forecast': '+18% forecast accuracy',
  'social_proof_metric_cash': 'Less capital in stock',
  'testimonial_1':
      'We cut stockouts in half in the first quarter. Clear recommendations, no more guesswork.',
  'testimonial_1_author': 'Operations Manager, E-commerce',
  'testimonial_2':
      'Finally we see what\'s at risk before it\'s too late. The reorder suggestions save us hours.',
  'testimonial_2_author': 'Supply Chain Lead, Retail',
  'problem_title': 'Sound familiar?',
  'problem_1_title': 'You lose sales to stockouts',
  'problem_1_desc':
      'Out-of-stock items mean lost revenue and customers who go elsewhere.',
  'problem_2_title': 'You tie up cash in excess inventory',
  'problem_2_desc':
      'Too much stock locks working capital and increases carrying costs.',
  'problem_3_title': 'You still rely on Excel',
  'problem_3_desc':
      'Spreadsheets can\'t keep up with demand and lead times in real time.',
  'problem_4_title': 'You decide reorders too late',
  'problem_4_desc':
      'By the time you notice, it\'s already critical. Reactive instead of proactive.',
  'solution_title': 'The solution',
  'solution_1_title': 'See products at risk',
  'solution_1_desc':
      'A clear view of what will run out and when. No more surprises.',
  'solution_2_title': 'Get reorder suggestions',
  'solution_2_desc':
      'We tell you what to order, when, and how much—based on your data.',
  'solution_3_title': 'Optimize capital in stock',
  'solution_3_desc':
      'Reduce overstock and free up cash without risking availability.',
  'problem_subtitle':
      'The problems you face every day in warehouse management.',
  'solution_subtitle': 'How FabricOS solves them.',
  'final_cta_title': 'Ready to take control of your inventory?',
  'view_all': 'View all',
  'view_plans': 'View plans',
  'recommended': 'Recommended',
  'status': 'Status',
  'next': 'Next',
  'back_to_login': 'Back to login',
  'send_reset_link': 'Send reset link',
  'email_check_title': 'Check your email',
  'email_check_message': 'We sent a reset link to',
  'manage_subscription': 'Manage subscription',
  'send': 'Send',
  'go_home': 'Go home',
  'dashboard_title': 'Dashboard',
  'features_section_title': 'Features',
  'name': 'Name',
  'message': 'Message',
  'plan_feature_workspace': '1 workspace',
  'plan_feature_users': 'users',
  'plan_feature_skus': 'Up to {count} SKUs',
  'plan_feature_csv': 'CSV imports',
  'plan_feature_basic_alerts': 'Basic alerts',
  'plan_feature_forecasting': 'Forecasting',
  'plan_feature_suppliers': 'Suppliers',
  'plan_feature_po': 'Purchase orders',
  'plan_feature_priority_support': 'Priority support',
  'plan_feature_advanced_alerts': 'Advanced alerts',
  'plan_feature_api': 'API access',
  'plan_feature_custom_limits': 'Custom limits',
  'plan_feature_sso': 'SSO',
  'plan_feature_dedicated_support': 'Dedicated support',
  'plan_feature_onboarding': 'Onboarding',
  'validation_name_required': 'Name required',
  'validation_email_required': 'Email required',
  'validation_password_min': 'Min 6 characters',
  'billing_trial_toggle_title': 'Start with 30-day trial',
  'billing_trial_toggle_subtitle': 'You can use all features and activate subscription later.',
  'billing_trial_30_days': '30-day trial',
  'billing_no_trial': 'No trial',
  'billing_subscribe_now': 'Subscribe now',
  'billing_seat_summary': 'Your subscription',
  'billing_required_title': 'Subscription required',
  'billing_required_subtitle': 'Activate a subscription to continue using the private app area.',
  'billing_open_page': 'Open billing and activate plan',
  'billing_active': 'Active subscription',
  'billing_trial_until': 'Trial active until',
  'billing_no_active': 'No active subscription',
  'billing_purchase_history': 'Payment history',
  'billing_no_purchases': 'No purchases yet.',
  'billing_all_features': 'All features included for every user.',
  'onboarding_company_setup_subtitle':
      'Create your company workspace and continue with your selected billing plan.',
  'pricing_how_many_users': 'How many users do you need?',
  'pricing_users': 'users',
  'pricing_per_user_month': 'per user / month',
  'pricing_volume_discounts': 'Volume discounts',
  'pricing_slider_hint': 'Use the slider or type any number of users',
  'pricing_all_included': 'All features included',
  'pricing_feat_dashboard': 'Decision dashboard',
  'pricing_feat_machines': 'Machine management',
  'pricing_feat_orders': 'Order management',
  'pricing_feat_suppliers': 'Supplier monitoring',
  'pricing_feat_ai_risk': 'AI risk & maintenance',
  'pricing_feat_demand': 'Demand forecasting',
  'pricing_feat_inventory': 'Inventory optimization',
  'pricing_feat_esg': 'ESG & compliance reports',
  'company_name': 'Company name',
  'company_size': 'Company size',
  'create_workspace_continue': 'Create workspace and continue',
  'team_title': 'Team',
  'team_subtitle': 'Manage users, roles, and menu visibility for your company.',
  'team_invite_title': 'Invite a new user',
  'team_invite_btn': 'Invite',
  'team_invite_success': 'User invited successfully.',
  'team_members_title': 'Members',
  'team_no_members': 'No team members yet.',
  'team_role': 'Role',
  'team_remove_confirm': 'Remove this member?',
  'team_permissions_title': 'Menu visibility per role',
  'team_select_company': 'Select a company to access',
  'copilot_title': 'Fabric Copilot',
  'copilot_subtitle':
      'Ask about delays, machines, inventory and supplier risk — powered by your live signals.',
  'copilot_hint': 'Ask a question…',
  'copilot_ask': 'Get insight',
  'copilot_locked': 'Copilot',
  'copilot_upgrade_hint': 'Upgrade to Growth to unlock AI Copilot.',
  'copilot_q1': 'Why are delays increasing?',
  'copilot_q2': 'Which machine needs attention?',
  'copilot_q3': 'What inventory should I reduce?',
  'copilot_q4': 'What supplier is risky?',
  'copilot_q5': 'What hurts margin most right now?',
  'exec_report_title': 'Daily CEO report',
  'exec_report_subtitle': 'Auto summary from today’s operational signals.',
  'exec_risk_today': 'Today’s risk',
  'exec_risk_elevated': 'Elevated — critical alerts need executive attention.',
  'exec_risk_normal': 'Normal — monitor standard queues.',
  'exec_money_lost': 'Money at risk (illustrative)',
  'exec_money_footnote': 'directional estimate from delays & alerts',
  'exec_top_issues': 'Top issues',
  'exec_no_alerts': 'No open alerts.',
  'exec_recommended': 'Recommended actions',
  'exec_rec_suppliers': 'Escalate delayed suppliers',
  'exec_rec_alerts': 'Triage open alerts by margin impact',
  'exec_rec_inventory': 'Validate coverage on A-class SKUs',
  'exec_email_template': 'Email template (copy for leadership)',
  'billing_plan_pick': 'Choose your plan',
  'billing_plan_subtitle': 'Flat monthly pricing — upgrade or downgrade anytime.',
  'billing_annual': 'Annual billing (~17% off)',
  'billing_checkout': 'Continue to secure checkout',
  'billing_iap_continue': 'Subscribe with App Store / Google Play',
  'billing_manage_in_store':
      'Manage or cancel this subscription in your App Store or Google Play account settings.',
  'billing_restore_purchases': 'Restore purchases',
  'billing_purchase_success': 'Subscription activated.',
  'billing_iap_timeout': 'Purchase is taking too long. You can finish subscribing from Billing in settings.',
  'billing_enterprise_note': 'Enterprise includes SSO, API and white-label — talk to sales.',
  'app_menu_executive': 'CEO report',
  'app_menu_simulation': 'What-if lab',
  'app_menu_control_tower': 'AI Control Tower',
  'app_menu_forecasting': 'Forecasts',
  'nav_section_operations': 'Operations',
  'nav_section_supply': 'Supply',
  'nav_section_intelligence': 'Intelligence',
  'nav_section_workspace': 'Workspace',
  'topbar_tagline':
      'Reduce downtime, delays and inventory waste — one intelligent platform for plants.',
  'topbar_chip_roi': 'ROI in 30 days',
  'topbar_chip_alerts': 'Live risk signals',
  'control_tower_title': 'AI Control Tower',
  'control_tower_subtitle':
      'Biggest risks, capital leakage, delays and prioritized actions in one view.',
  'control_tower_health': 'Operational health',
  'control_tower_leak': 'Est. monthly leakage',
  'control_tower_leak_suffix': ' directional',
  'control_tower_delays': 'Suppliers behind',
  'control_tower_delays_suffix': ' active',
  'control_tower_alerts': 'Critical alerts',
  'control_tower_critical_suffix': ' open',
  'control_tower_risks': 'Top risks',
  'control_tower_actions': 'Recommended actions',
  'control_tower_no_actions': 'No rule-based actions — data looks calm.',
  'book_demo_title': 'Book a FabricOS demo',
  'book_demo_subtitle':
      '30 minutes with our team: map your plants, pain points, and a realistic 30-day rollout.',
  'book_demo_cta_calendar': 'Open calendar',
  'book_demo_cta_form': 'Prefer a form? Contact us',
  'book_demo_footnote': 'Replace the calendar link with your Cal.com, Calendly or HubSpot meeting URL.',
  'onboarding_intro_body':
      'Answer a few questions so we can tailor ROI and your workspace — about two minutes.',
  'onboarding_step_welcome': 'Welcome',
  'onboarding_step_company': 'Company',
  'onboarding_step_plants': 'Plants',
  'onboarding_step_machines': 'Machines',
  'onboarding_step_pain': 'Main pain',
  'onboarding_step_roi': 'Your ROI preview',
  'onboarding_plants_label': 'Number of plants',
  'onboarding_machines_label': 'Approx. connected machines',
  'onboarding_pain_label': 'What hurts most today?',
  'onboarding_pain_downtime': 'Unplanned downtime',
  'onboarding_pain_delays': 'Supplier delays',
  'onboarding_pain_inventory': 'Excess / wrong inventory',
  'onboarding_pain_visibility': 'Lack of visibility (spreadsheets)',
  'onboarding_roi_blurb':
      'Illustrative savings if you consolidate signals and act earlier — not financial advice.',
  'onboarding_back': 'Back',
  'onboarding_next': 'Next',
};
