const Map<String, String> appLocalizationsEn = {
  'app_name': 'StockGuard AI',
  'tagline': 'The autopilot for your warehouse.',
  'hero_title': 'Stop stockouts before they happen.',
  'hero_subtitle':
      'StockGuard AI helps e-commerce brands, distributors, and manufacturers know what to reorder, when to reorder it, and how much to buy.',
  'cta_start_trial': 'Start free trial',
  'cta_book_demo': 'Book a demo',
  'cta_get_started': 'Get started',
  'cta_sign_in': 'Sign in',
  'cta_sign_up': 'Sign up',
  'nav_features': 'Features',
  'nav_solutions': 'Solutions',
  'nav_pricing': 'Pricing',
  'nav_about': 'About',
  'nav_contact': 'Contact',
  'nav_faq': 'FAQ',
  'nav_blog': 'Blog',
  'nav_login': 'Log in',
  'nav_register': 'Register',
  'footer_privacy': 'Privacy Policy',
  'footer_terms': 'Terms of Service',
  'footer_cookies': 'Cookie Policy',
  'footer_contact': 'Contact',
  'login_title': 'Welcome back',
  'login_subtitle': 'Sign in to your account',
  'login_email': 'Email',
  'login_password': 'Password',
  'login_forgot': 'Forgot password?',
  'register_title': 'Create your account',
  'register_subtitle': 'Start your free trial',
  'register_name': 'Full name',
  'register_company': 'Company name',
  'forgot_title': 'Reset password',
  'forgot_subtitle': 'Enter your email to receive a reset link',
  'reset_title': 'Set new password',
  'dashboard': 'Dashboard',
  'products': 'Products',
  'product_detail': 'Product detail',
  'reorder_suggestions': 'Reorder suggestions',
  'forecasting': 'Forecasting',
  'suppliers': 'Suppliers',
  'alerts': 'Alerts',
  'purchase_orders': 'Purchase orders',
  'analytics': 'Analytics',
  'billing': 'Billing',
  'settings': 'Settings',
  'profile': 'Profile',
  'company': 'Company',
  'team': 'Team',
  'notifications': 'Notifications',
  'language': 'Language',
  'sign_out': 'Sign out',
  'products_at_risk': 'Products at risk',
  'overstocked': 'Overstocked',
  'reorder_today': 'Reorder today',
  'inventory_value': 'Inventory value',
  'capital_locked': 'Capital locked',
  'supplier_risk': 'Supplier risk',
  'empty_state_title': 'No data yet',
  'empty_state_subtitle': 'Import your first data or connect a source.',
  'onboarding_welcome': 'Welcome to StockGuard AI',
  'onboarding_company': 'Set up your company',
  'onboarding_data': 'Connect your data',
  'onboarding_done': "You're all set",
  'plan_starter': 'Starter',
  'plan_growth': 'Growth',
  'plan_pro': 'Pro',
  'plan_enterprise': 'Enterprise',
  'per_month': '/month',
  'per_year': '/year',
  'contact_sales': 'Contact sales',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'search': 'Search',
  'filter': 'Filter',
  'loading': 'Loading...',
  'error_generic': 'Something went wrong. Please try again.',
  'sku': 'SKU',
  'current_stock': 'Current stock',
  'reorder_point': 'Reorder point',
  'lead_time_days': 'Lead time (days)',
  'unit_cost': 'Unit cost',
  'selling_price': 'Selling price',
  'stock_coverage_days': 'Coverage (days)',
  'status_safe': 'Safe',
  'status_attention': 'Attention',
  'status_critical': 'Critical',
  'import_csv': 'Import CSV',
  'home': 'Home',
  'help': 'Help',
  'demo': 'Demo',
  'hero_headline_benefit': 'Avoid stockouts and capital tied up in warehouse',
  'hero_subheadline_one_line': 'StockGuard AI tells you what to reorder, when to do it, and how much to buy.',
  'cta_try_free': 'Try free',
  'cta_watch_demo': 'Watch demo',
  'cta_see_how': 'See how it works',
  'cta_start_now': 'Start now',
  'social_proof_title': 'Trusted by operations and supply chain teams',
  'social_proof_companies': '500+ companies',
  'social_proof_metric_stockout': '-22% stockouts',
  'social_proof_metric_forecast': '+18% forecast accuracy',
  'social_proof_metric_cash': 'Less capital in stock',
  'testimonial_1': 'We cut stockouts in half in the first quarter. Clear recommendations, no more guesswork.',
  'testimonial_1_author': 'Operations Manager, E-commerce',
  'testimonial_2': 'Finally we see what\'s at risk before it\'s too late. The reorder suggestions save us hours.',
  'testimonial_2_author': 'Supply Chain Lead, Retail',
  'problem_title': 'Sound familiar?',
  'problem_1_title': 'You lose sales to stockouts',
  'problem_1_desc': 'Out-of-stock items mean lost revenue and customers who go elsewhere.',
  'problem_2_title': 'You tie up cash in excess inventory',
  'problem_2_desc': 'Too much stock locks working capital and increases carrying costs.',
  'problem_3_title': 'You still rely on Excel',
  'problem_3_desc': 'Spreadsheets can\'t keep up with demand and lead times in real time.',
  'problem_4_title': 'You decide reorders too late',
  'problem_4_desc': 'By the time you notice, it\'s already critical. Reactive instead of proactive.',
  'solution_title': 'The solution',
  'solution_1_title': 'See products at risk',
  'solution_1_desc': 'A clear view of what will run out and when. No more surprises.',
  'solution_2_title': 'Get reorder suggestions',
  'solution_2_desc': 'We tell you what to order, when, and how much—based on your data.',
  'solution_3_title': 'Optimize capital in stock',
  'solution_3_desc': 'Reduce overstock and free up cash without risking availability.',
  'problem_subtitle': 'The problems you face every day in warehouse management.',
  'solution_subtitle': 'How StockGuard AI solves them.',
  'final_cta_title': 'Ready to take control of your inventory?',
  'view_all': 'View all',
  'view_plans': 'View plans',
  'recommended': 'Recommended',
  'status': 'Status',
  'next': 'Next',
  'back_to_login': 'Back to login',
  'send_reset_link': 'Send reset link',
  'email_check_title': 'Check your email',
  'email_check_message': 'We sent a reset link to',
  'manage_subscription': 'Manage subscription',
  'send': 'Send',
  'go_home': 'Go home',
  'dashboard_title': 'Dashboard',
  'features_section_title': 'Features',
  'name': 'Name',
  'message': 'Message',
  'plan_feature_workspace': '1 workspace',
  'plan_feature_users': 'users',
  'plan_feature_skus': 'Up to {count} SKUs',
  'plan_feature_csv': 'CSV imports',
  'plan_feature_basic_alerts': 'Basic alerts',
  'plan_feature_forecasting': 'Forecasting',
  'plan_feature_suppliers': 'Suppliers',
  'plan_feature_po': 'Purchase orders',
  'plan_feature_priority_support': 'Priority support',
  'plan_feature_advanced_alerts': 'Advanced alerts',
  'plan_feature_api': 'API access',
  'plan_feature_custom_limits': 'Custom limits',
  'plan_feature_sso': 'SSO',
  'plan_feature_dedicated_support': 'Dedicated support',
  'plan_feature_onboarding': 'Onboarding',
};
