import 'package:fabricos/features/app_shell/providers/fabricos_provider.dart';
import 'package:fabricos/features/supply_chain/data/supply_chain_ai_service.dart';
import 'package:fabricos/localization/app_localizations.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Daily CEO-style summary from live workspace signals (no separate backend).
class ExecutiveReportPage extends ConsumerWidget {
  const ExecutiveReportPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final l10n = context.l10n;
    final snapAsync = ref.watch(dashboardSnapshotProvider);
    final alertsAsync = ref.watch(alertsProvider);
    final invAsync = ref.watch(inventoryProvider);

    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: snapAsync.when(
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) => Text('$e'),
            data: (snap) {
              final alerts = alertsAsync.valueOrNull ?? const [];
              final inv = invAsync.valueOrNull ?? const [];
              final critical = alerts.where((a) => a['severity'] == 'critical').length;
              final estLoss = (snap.delayedSuppliers * 4200 + snap.openAlerts * 900).toDouble();

              final emailBody = '''
FabricOS — Daily CEO Report
Date: ${DateTime.now().toIso8601String().split('T').first}

Today's risk: ${critical > 0 ? 'ELEVATED' : 'NORMAL'} ($critical critical alerts)
Money at risk (illustrative): €${estLoss.toStringAsFixed(0)}

Top issues:
${alerts.take(5).map((a) => '- ${a['title']}: ${a['message']}').join('\n')}

Recommended actions:
- Review suppliers with active delays (${snap.delayedSuppliers})
- Clear or escalate open alerts (${snap.openAlerts})
- Validate inventory coverage on top SKUs (${inv.length} rows tracked)

— Generated by FabricOS Executive Report
''';

              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    l10n.t('exec_report_title'),
                    style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                          color: const Color(0xFFEAF2FF),
                          fontWeight: FontWeight.w700,
                        ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    l10n.t('exec_report_subtitle'),
                    style: const TextStyle(color: Color(0xFF8EA3C2)),
                  ),
                  const SizedBox(height: 24),
                  _glassCard(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(l10n.t('exec_risk_today'), style: _h),
                        const SizedBox(height: 8),
                        Text(
                          critical > 0 ? l10n.t('exec_risk_elevated') : l10n.t('exec_risk_normal'),
                          style: const TextStyle(color: Color(0xFFEAF2FF), fontSize: 16),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 16),
                  _glassCard(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(l10n.t('exec_money_lost'), style: _h),
                        const SizedBox(height: 8),
                        Text(
                          '€${estLoss.toStringAsFixed(0)} ${l10n.t('exec_money_footnote')}',
                          style: const TextStyle(color: Color(0xFFFBBF24), fontSize: 18, fontWeight: FontWeight.w600),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 16),
                  _glassCard(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(l10n.t('exec_top_issues'), style: _h),
                        const SizedBox(height: 8),
                        if (alerts.isEmpty)
                          Text(l10n.t('exec_no_alerts'), style: const TextStyle(color: Color(0xFF8EA3C2)))
                        else
                          ...alerts.take(6).map(
                                (a) => Padding(
                                  padding: const EdgeInsets.only(bottom: 10),
                                  child: Row(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      const Icon(Icons.chevron_right, color: Color(0xFF7DD3FC), size: 18),
                                      Expanded(
                                        child: Text(
                                          '${a['title'] ?? 'Alert'} — ${a['message'] ?? ''}',
                                          style: const TextStyle(color: Color(0xFFCBD5E1), height: 1.4),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 16),
                  _glassCard(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(l10n.t('exec_recommended'), style: _h),
                        const SizedBox(height: 8),
                        Text(
                          '• ${l10n.t('exec_rec_suppliers')} (${snap.delayedSuppliers})\n'
                          '• ${l10n.t('exec_rec_alerts')} (${snap.openAlerts})\n'
                          '• ${l10n.t('exec_rec_inventory')}',
                          style: const TextStyle(color: Color(0xFFCBD5E1), height: 1.5),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 24),
                  Text(l10n.t('exec_email_template'), style: _h),
                  const SizedBox(height: 8),
                  SelectableText(
                    emailBody,
                    style: const TextStyle(color: Color(0xFF94A3B8), fontSize: 12, height: 1.45),
                  ),
                ],
              );
            },
          ),
        ),
      ),
    );
  }

  static const _h = TextStyle(color: Color(0xFFEAF2FF), fontSize: 15, fontWeight: FontWeight.w600);

  static Widget _glassCard({required Widget child}) {
    return DecoratedBox(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFF1F2937)),
        gradient: const LinearGradient(
          colors: [Color(0xE60F172A), Color(0xCC0B1220)],
        ),
      ),
      child: Padding(padding: const EdgeInsets.all(18), child: child),
    );
  }
}
