import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { enforceCompanyFeature } from '../_shared/plan_entitlements.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return json({ error: 'Unauthorized' }, 401);

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
    { global: { headers: { Authorization: authHeader } } }
  );

  const {
    data: { user },
  } = await supabase.auth.getUser(authHeader.replace('Bearer ', ''));
  if (!user) return json({ error: 'Unauthorized' }, 401);

  try {
    const body = await req.json().catch(() => ({}));
    let companyId = body.companyId as string | undefined;

    if (!companyId) {
      const { data: profile } = await supabase
        .from('users')
        .select('company_id')
        .eq('id', user.id)
        .maybeSingle();
      companyId = profile?.company_id;
    }

    if (!companyId) {
      return json({ error: 'companyId is required' }, 400);
    }

    const denied = await enforceCompanyFeature(
      supabase,
      user.id,
      companyId,
      'esg',
      json,
    );
    if (denied) return denied;

    const rawMonth = body.reportMonth as string | undefined;
    const monthDate = rawMonth ? new Date(rawMonth) : new Date();
    const reportMonth = `${monthDate.getUTCFullYear()}-${String(monthDate.getUTCMonth() + 1).padStart(2, '0')}-01`;

    const { data: machineRows } = await supabase
      .from('machines')
      .select('status')
      .eq('company_id', companyId);

    const { data: orderRows } = await supabase
      .from('orders')
      .select('delay_days, status')
      .eq('company_id', companyId);

    const { data: supplierRows } = await supabase
      .from('suppliers')
      .select('compliance_status, reliability_score, avg_delay_days')
      .eq('company_id', companyId);

    const warningMachines = (machineRows ?? []).filter((m) => m.status === 'warning').length;
    const stoppedMachines = (machineRows ?? []).filter((m) => m.status === 'stopped').length;
    const delayedOrders = (orderRows ?? []).filter((o) => (o.delay_days ?? 0) > 0 && o.status !== 'completed').length;

    const complianceWeights = (supplierRows ?? []).map((s) => {
      const status = (s.compliance_status ?? 'under_review') as string;
      if (status === 'compliant') return 95;
      if (status === 'under_review') return 75;
      return 45;
    });

    const supplierComplianceScore =
      complianceWeights.length === 0
        ? 75
        : complianceWeights.reduce((sum, value) => sum + value, 0) / complianceWeights.length;

    // Mock emissions baseline based on operational stress indicators.
    const emissionsTco2 =
      42 + warningMachines * 2.6 + stoppedMachines * 4.4 + delayedOrders * 1.35 + Math.random() * 3;

    const summary =
      `Monthly ESG snapshot generated by FabricOS AI. ` +
      `${warningMachines} machines in warning, ${stoppedMachines} stopped, ` +
      `${delayedOrders} delayed orders. Supplier compliance score ${supplierComplianceScore.toFixed(1)}.`;

    const payload = {
      company_id: companyId,
      report_month: reportMonth,
      emissions_tco2: Number(emissionsTco2.toFixed(3)),
      supplier_compliance_score: Number(supplierComplianceScore.toFixed(2)),
      summary,
      metadata: {
        warning_machines: warningMachines,
        stopped_machines: stoppedMachines,
        delayed_orders: delayedOrders,
        model: 'mock-esg-v1',
      },
      created_by: user.id,
      updated_at: new Date().toISOString(),
    };

    const { data: report, error } = await supabase
      .from('esg_reports')
      .upsert(payload, { onConflict: 'company_id,report_month' })
      .select()
      .single();

    if (error || !report) {
      return json({ error: error?.message ?? 'Failed to generate report' }, 500);
    }

    return json(report);
  } catch (error) {
    return json({ error: String(error) }, 500);
  }
});
